apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: openlex-eks-demo
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: "v1.16.*"
    helm:
      valuesObject:
        installCRDs: true
        resources:
          requests: { cpu: 25m, memory: 64Mi }
          limits: { cpu: 100m, memory: 128Mi }
        webhook:
          resources:
            requests: { cpu: 10m, memory: 32Mi }
            limits: { cpu: 50m, memory: 64Mi }
        cainjector:
          resources:
            requests: { cpu: 10m, memory: 64Mi }
            limits: { cpu: 50m, memory: 128Mi }
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
